### ISSUE TITLE
Expose a function that can be used in templates

### ISSUE THREAD

**Issue by mrksbnch** [jancbeck/kirby-responsive-images#8]
As far as I can tell, this plugin currently only adds the `srcset` and `sizes` attributes to images that are used in kirbytext. What about the other images in a page, e.g. those that are included in a template?

``` yaml
headerimg:
    label: Image Label
    type: image
    required: true
```

``` html
<img src="<?php echo $page->image($page->headerimg())->url() ?>" alt="...">
```
